---
title: "The Now" 
date: "2024-01-29" 
categories: now 
reference-location: margin
citation-location: margin
---

## What is The Now?

So this standing section will be a general reflection on what's going in my life *right now*. Generally it's a practice in mindfulness [Obligatory h/t to good friend and fellow blogger [Tan Ho](http://tanho.ca/now)'s now page for my inspiration]{.aside}. For more information, [this](https://nownownow.com/about) is a good explainer.

## New Year, ~~New Me~~ More Sustainable Goals

January is a natural goal-setting month. Like most people, I initially rushed to improve what I saw were the worst parts of myself.

Then I reread that last sentence. Then I was sad.

I once thought that the quickest way to self-improvement comes was a counterweight of self-loathing urgency. I don't think it's terribly uncommon. For me, it tends to sound like:

> "\[Insert Unattainable Habit to Adopt\] needs to happen **IMMEDIATELY** *because **everything is so awful**!!!!!*"

It works, but it is also absolutely exhausting: I've seen plenty of front-end improvement only to burn out easily and often.

Through this experience, I am beginning to learn that **slow progress is lasting progress**. More specifically, progress for me will require **patiently re-framing my scarcity mindset**, including:

-   ***accepting*** how far I've come (*I'm not starting from scratch. Everything is not awful.*)
-   ***celebrating*** my growth and learning from my mistakes (*In fact, everything is pretty good! I've accomplished a ton, including many mistakes.*[Sneaky re-frame: Mistakes are progress!]{.aside})
-   ***trusting myself*** to stay present and keep executing, leave the future for the future. (*The opportunities I'm chasing will present themselves often. I trust myself to be as present as possible when they arrive.*).

So this year, I'm not throwing out the old me. I'm staying present with the current version of myself, and building toward the following milestones:

1.  **Rebuild Back to Full Strength, Physically and Financially\
    **My knee injury from lifting was just judged not to need an MRI (yay!). More great news is that I've kept off the 20 pounds I lost last year during the recovery process. Looking for more, but staying patient and staying strong.\
    \
    Financially I'm riding through some turbulence thanks to some early-year emergencies, but we're getting back on track after an eventful 2023.

2.  **Keep Building Upon Healthier Habits, and Fail Often\
    **Namely, I'm keeping my spaces clean and relatively uncluttered. We're starting there and building out. I'm also developing the habit of writing every day, which leads to...

3.  **Get That Portfolio Up!\
    **That's the point of this website. I've been sitting on serious soccer analysis for years, but I've struggled to keep the ideas in my head because life is busy. Dedicating more time to documenting my process will be important and helpful. We'll see how it goes!

## Other Things I'm Doing

### Planning Golf Trips

[Find me on social media and feel free to DM course suggestions!]{.aside} I'd love to get back to the American Soccer Golf Tour this year. Current candidates are as follows, suggestions welcome:

**Charleston, SC** - Kiawah Island is a must for any golfer, and a [Charleston Battery](https://www.charlestonbattery.com/2024-schedule/) match seems like a must for any soccer historian.

**Raleigh, NC** - Tobacco Road is a must and I have to see if the [NC Courage](https://www.nccourage.com/schedule/) are a bigger draw than NCFC.

**Louisville, KY** - [Renting hickory clubs](https://louisvillegolf.com/) and traveling back in time, then heading to a [Lou City](https://www.loucity.com/schedule/) or [Racing Louisville](https://www.racingloufc.com/schedule/) match. [By the way, Racing Louisville's [houndstooth kit](https://lousoccerstore.com/products/racing-2023-mens-home-jersey) is absolute 🔥🔥🔥.]{.aside}

**Atlanta, GA** - The soccer nerd vibes at a packed ATL United Game have been on the list since I saw the Footie Mob for the first time. Course suggestions are welcome.

### Current Mood: 😖▶️🙃

**Annoyed, but confident.** I've been dealing with some early-year emergencies lately (nothing I'll get into here). However, I'm pretty proud of my response so far. Upon reflection, I want to be able to handle my stress while being able to function clearly. And if I can't, I want to be able to confront what or who is bothering me head-on, while remaining composed and affable.

Trying to be patient as possible: the problems remain stubborn and will likely stay problems for the next few months.

There will always be problems. I can control what I can control, and I can control my response to the things I can't control.
